image: php:7.3-fpm

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -qy git curl libmcrypt-dev postgresql-contrib libpq-dev unzip
          - yes | pecl install mcrypt-1.0.2
          - docker-php-ext-install pdo_pgsql pcntl

          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - ln -f -s .env.pipelines .env
          - php artisan migrate
          - php artisan key:generate
          - php artisan serve &
          - sleep 5
          - ./vendor/bin/phpunit
          - curl -vk http://localhost:8000
        services:
          - postgres

definitions:
  services:
    postgres:
      image: postgres:11.7
      environment:
        POSTGRES_DB: 'safetrade_test'
        POSTGRES_USER: 'homestead'
        POSTGRES_PASSWORD: 'secret'
